# Configuration file for Travis CI builds,
# which are automatically run when code is pushed to Github.
# To skip a build, add [ci skip] to the commit message.
# This file has been linted using: http://lint.travis-ci.org/

# Use PHP, to run unit tests
language: php

# PHP versions to test against
# https://github.com/meitar/wordpress-plugin-skeleton/blob/master/.travis.yml
php:
  - 5.6.30 # MAMP
#  - 5.5 # Sitehost - fails phpunit version requirement

# Public Environment Variables
# https://docs.travis-ci.com/user/environment-variables
# https://github.com/meitar/wordpress-plugin-skeleton/blob/master/.travis.yml
env:
  - WP_VERSION=latest WP_MULTISITE=0

# Build Matrix
# consisting of specific runtime/env/exclude/include combinations.
# Each 'include' is run as a separate job.
# https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix
# https://github.com/meitar/wordpress-plugin-skeleton/blob/master/.travis.yml
matrix:
  # reduce the delay in the build status being reported
  # https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
  fast_finish: true
  include:
    - php: 5.6.30
      env: WP_VERSION=latest WP_MULTISITE=0

# Cache directories between builds, to store dependencies
# which take longer to compile or download.
# https://docs.travis-ci.com/user/caching#Caching-directories-(Bundler%2C-dependencies)
# https://github.com/wp-cli/sample-plugin/blob/master/.travis.yml
# https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
# ~/files - https://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/
cache:
  directories:
#   - node_modules
#   - vendor
#    - $HOME/.composer/cache/files
    - $HOME/.npm 

# Install a Second Programming Language (Node, to run Gulp tasks)
# We need to specify a newer version than the Travis default
# in order to avoid the build error "Use of const in strict mode"
# https://docs.travis-ci.com/user/customizing-the-build/#Installing-a-Second-Programming-language
# https://stackoverflow.com/a/44250453/6850747
before_install:
  - nvm install 6.11.2
  # Disable XDebug which is only required for Code Coverage reports
  # https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
  - phpenv config-rm xdebug.ini

# Install dependencies
# https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Installation-Step
# Note: Remember to run composer update on local dev to get latest updates to dependencies
install:
  - composer install --no-interaction # also run via gulpfile.js
  - npm install
  - npm install bower -g
# - bower install - run via gulpfile.js
  - npm install gulp-cli -g
  # https://www.sitepoint.com/php-continuous-integration-travis-ci/
  # https://getcomposer.org/doc/03-cli.md

# https://github.com/wp-cli/sample-plugin/blob/master/.travis.yml
before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

# Run the build script
script:
  - gulp dist
  - phpunit

# Notifications of build results
# https://docs.travis-ci.com/user/notifications/
notifications:
  email: false
  slack: dotherightthing:Wu2ypwc2wIFZVqVqc2jRkbWw

# Deploy code to Github as a 'release'
# This is run after a tagged commit triggers a successful build
# release.zip is generated by gulp dist
# api_key is generated via: travis setup releases
# which requires my GH username and password
# and creates a Personal Access Token at https://github.com/settings/tokens
# named 'automatic releases for dotherightthing/wpdtrt-gallery' 
# https://docs.travis-ci.com/user/deployment/releases/
deploy:
  provider: releases
  api_key:
    secure: nMzWhTpJL7m/d8whVuWaE1IgHZHOkZUGRbMHu5lk5GGO21wbkM1fvtGtlhhkEfsI6GM0IloCQejqNEYQ1cg4wCW4BatSSMat7sa5lu0Pk2NZt9BGQP/5NOx4KsngjeGEt5sa5XJzPfe0kBQ3+YTjUhLX9TbI1KohExOZX75pw4eTgryGdQJuXP/RtQZCEmqC9wSjUzIl06kkVV5321dJChiSLb2v9UqSqbMPOihLA3PX3Y/eXXOSVDH5/WjeyriDlAaVhXKgxNyAL+hOGIdLctFmNqvh7RlHIOE6U0s8i1j7KnMAw37/hkvugUo30QIpAdy76jISL6L0jVpZ4V5POtdLE1CmfmhczgpVi6qfrXLD1RVo/IC3nNYnuo8edHUyPv4IKYsbe/UcweDrkcCsZzSBd8zBl5W05hGfGF799W9guZ2i3D7OIB2JlHE6N+GID00gAU1lFFyTRUG8d38Beuq4t0HCqSo0opY31GILs7o/UOHtbznttVjtfSBApwjcg/rf+uBjq9OqjyxbuIOeHF/qy8S1572tCOapf+T9+L7VxuGqaRLCBPXV9KUhdNIKrqT7NdIH6iiq2wCkyOB+A7DEUzULBy9INATQqhPqIAK1ytQxPModNDttgLDeizsNwvLnsKlh5MYXmwI2Ma5NAMiOu4vFQAbor6xmxzP6OSc=
  file: 'release.zip'
  # prevent Travis CI from resetting the working directory
  # which deletes all changes made during the build 
  skip_cleanup: true
  on:
    repo: dotherightthing/wpdtrt-gallery
    tags: true
    # https://stackoverflow.com/a/27775257/6850747
    all_branches: true
