language: node_js
# Use newer version than the Travis default
# to avoid build error "Use of const in strict mode"
node_js:
- 6.11.2
install:
- npm install
- npm install -g bower
- bower install
script:
- gulp dist
notifications:
  email: false
  slack: dotherightthing:Wu2ypwc2wIFZVqVqc2jRkbWw
# Automatically create release.zip after a tagged commit triggers a successful build
# https://docs.travis-ci.com/user/deployment/releases/
deploy:
  provider: releases
  api_key:
    secure: jMGVI+/+GV2EfKAGtmo/QYcrir/1Ub6hBMbGTYUh6C1Wba4orjzX31OpJkDfC8fRaJMtLDuTmp5OVC0mwppMszOnhVBq4Z+duKiXRud0UCoo+kZ2jkMX6w0J2Pmd1Ha6cmbEM6KKmTBgBm6UmhWnfhBfNpvrcpkWWBdU0Wh36oOKr6Rg6vZD07k4A+uqZ5UPkf+ToKYDtdmG7enlwgDva1HpnFo12qUn5Pwokx2GliMAvbX5pyFrIuTEfRVkFop9uWV+cCOYV62bwzmhwIKVV+7YKYtdRjzk4LgJrRQpjH02dWkhk8dDiJgBfDdEvJh3zWqg+AiqO0JaMN0lDVkm575qSFgzMph8yKso/nRnCx4NhgxkoqFH/gdL3Yob9Nmn30trSAVe1349eCcnbCLtxnks2VnwywfnRShIaWPLqfnx/bpGpGq/tCHsozi9ZrCdyZB6tmdxbrc1m/zZG25xGJAY/2Af2DVfT5jq7WTzTI50rg9D53jkKNQemYtITcinX9GXmnqXNpK4/Y+4ueI3R9gURsB4YDjYPf8SyHja+rzwCRoR7428mRUkONjTJFNLxyD7q/xFXcDln89BVWjRWaj09Sa4c49fouigz/APs0mVba9h8IoxhT6C7a4yeRDXT+2KWzFiRJGZ2Nt3Ew3EUpmUSxzX4tDsPZljOKdoDEk=
  file: release.zip
  skip_cleanup: true
  on:
    repo: dotherightthing/wpdtrt-gallery
    branch: master
    tags: true
