# Configuration file for Travis CI builds,
# which are automatically run when code is pushed to Github.
# To skip a build, add [ci skip] to the commit message.
# This file has been linted using: http://lint.travis-ci.org/

# Use PHP, to run unit tests
language: php

# PHP versions to test against
# https://github.com/meitar/wordpress-plugin-skeleton/blob/master/.travis.yml
php:
  - 5.6.30 # MAMP
#  - 5.5 # Sitehost - fails phpunit version requirement

# Public Environment Variables
# https://docs.travis-ci.com/user/environment-variables
# https://github.com/meitar/wordpress-plugin-skeleton/blob/master/.travis.yml
env:
  - WP_VERSION=latest WP_MULTISITE=0

# Build Matrix
# consisting of specific runtime/env/exclude/include combinations.
# Each 'include' is run as a separate job.
# https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix
# https://github.com/meitar/wordpress-plugin-skeleton/blob/master/.travis.yml
matrix:
  # reduce the delay in the build status being reported
  # https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
  fast_finish: true
  include:
    - php: 5.6.30
      env: WP_VERSION=latest WP_MULTISITE=0

# Cache directories between builds, to store dependencies
# which take longer to compile or download.
# https://docs.travis-ci.com/user/caching#Caching-directories-(Bundler%2C-dependencies)
# https://github.com/wp-cli/sample-plugin/blob/master/.travis.yml
# https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
cache:
  directories:
#   - node_modules
#   - vendor
    - $HOME/.composer/cache
    - $HOME/.npm 

# Install a Second Programming Language (Node, to run Gulp tasks)
# We need to specify a newer version than the Travis default
# in order to avoid the build error "Use of const in strict mode"
# https://docs.travis-ci.com/user/customizing-the-build/#Installing-a-Second-Programming-language
# https://stackoverflow.com/a/44250453/6850747
before_install:
  - nvm install 6.11.2
  # Disable XDebug which is only required for Code Coverage reports
  # https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
  - phpenv config-rm xdebug.ini

# Install dependencies
# https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Installation-Step
install:
  - npm install
  - npm install bower -g
  - npm install gulp-cli -g
  - bower install
  # https://www.sitepoint.com/php-continuous-integration-travis-ci/
  # https://getcomposer.org/doc/03-cli.md
  - composer install --no-interaction

# https://github.com/wp-cli/sample-plugin/blob/master/.travis.yml
before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

# Run the build script
script:
  - gulp dist
  - phpunit

# Notifications of build results
# https://docs.travis-ci.com/user/notifications/
notifications:
  email: false
  slack: dotherightthing:Wu2ypwc2wIFZVqVqc2jRkbWw

# Deploy code to Github as a 'release'
# This is run after a tagged commit triggers a successful build
# release.zip is generated by gulp dist
# https://docs.travis-ci.com/user/deployment/releases/
deploy:
  provider: releases
  api_key:
    secure: jMGVI+/+GV2EfKAGtmo/QYcrir/1Ub6hBMbGTYUh6C1Wba4orjzX31OpJkDfC8fRaJMtLDuTmp5OVC0mwppMszOnhVBq4Z+duKiXRud0UCoo+kZ2jkMX6w0J2Pmd1Ha6cmbEM6KKmTBgBm6UmhWnfhBfNpvrcpkWWBdU0Wh36oOKr6Rg6vZD07k4A+uqZ5UPkf+ToKYDtdmG7enlwgDva1HpnFo12qUn5Pwokx2GliMAvbX5pyFrIuTEfRVkFop9uWV+cCOYV62bwzmhwIKVV+7YKYtdRjzk4LgJrRQpjH02dWkhk8dDiJgBfDdEvJh3zWqg+AiqO0JaMN0lDVkm575qSFgzMph8yKso/nRnCx4NhgxkoqFH/gdL3Yob9Nmn30trSAVe1349eCcnbCLtxnks2VnwywfnRShIaWPLqfnx/bpGpGq/tCHsozi9ZrCdyZB6tmdxbrc1m/zZG25xGJAY/2Af2DVfT5jq7WTzTI50rg9D53jkKNQemYtITcinX9GXmnqXNpK4/Y+4ueI3R9gURsB4YDjYPf8SyHja+rzwCRoR7428mRUkONjTJFNLxyD7q/xFXcDln89BVWjRWaj09Sa4c49fouigz/APs0mVba9h8IoxhT6C7a4yeRDXT+2KWzFiRJGZ2Nt3Ew3EUpmUSxzX4tDsPZljOKdoDEk=
  file: 'release.zip'
  # prevent Travis CI from resetting the working directory
  # which deletes all changes made during the build 
  skip_cleanup: true
  on:
    repo: dotherightthing/wpdtrt-gallery
    branch: master
    tags: true
