# Bitbucket Pipeline configuration
# Runs on a Docker image
# Note: use only spaces to indent
#
# See https://www.savjee.be/2016/06/Deploying-website-to-ftp-or-amazon-s3-with-BitBucket-Pipelines/
# See https://confluence.atlassian.com/x/5Q4SMw for more examples.
#
# Uses https://github.com/git-ftp/git-ftp
# Initial upload of all files:
# - git ftp init --user $FTP_USERNAME_DEV --passwd $FTP_PASSWORD_DEV $FTP_SERVER_PATH_DEV
# Update with only files from the latest commit:
# git ftp push --user $FTP_USERNAME_DEV --passwd $FTP_PASSWORD_DEV $FTP_SERVER_PATH_DEV

image: samueldebruyn/debian-git

pipelines:
  branches:
    staging:
    - step:
        script:
          - apt-get update
          - apt-get -qq install git-ftp
          - git ftp init --user $FTP_USERNAME_DEV --passwd $FTP_PASSWORD_DEV $FTP_SERVER_PATH_DEV